import Head from "next/head";
import { useState } from "react";
import type { FuseResult } from "fuse.js";

const names = ["Tim", "Joe", "Bel", "Lee"];

export default function Search() {
	const [results, setResults] = useState<Array<FuseResult<string>>>([]);
	return (
		<>
			<Head>
				<title>Search</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<input
					type="text"
					placeholder="Search"
					onChange={async (e) => {
						const { value } = e.currentTarget;
						// Dynamically load fuse.js
						const Fuse = (await import("fuse.js")).default;
						const fuse = new Fuse(names);

						setResults(fuse.search(value));
					}}
				/>
				<pre>Results: {JSON.stringify(results, null, 2)}</pre>
			</div>
		</>
	);
}
